/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VagasIndexRouteImport } from './routes/vagas.index'
import { Route as VagasSlugRouteImport } from './routes/vagas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasIndexRoute = VagasIndexRouteImport.update({
  id: '/vagas/',
  path: '/vagas/',
  getParentRoute: () => rootRouteImport,
} as any)
const VagasSlugRoute = VagasSlugRouteImport.update({
  id: '/vagas/$slug',
  path: '/vagas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas/': typeof VagasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas': typeof VagasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/vagas/$slug': typeof VagasSlugRoute
  '/vagas/': typeof VagasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/vagas/$slug' | '/vagas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/vagas/$slug' | '/vagas'
  id: '__root__' | '/' | '/vagas/$slug' | '/vagas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VagasSlugRoute: typeof VagasSlugRoute
  VagasIndexRoute: typeof VagasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/': {
      id: '/vagas/'
      path: '/vagas'
      fullPath: '/vagas/'
      preLoaderRoute: typeof VagasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vagas/$slug': {
      id: '/vagas/$slug'
      path: '/vagas/$slug'
      fullPath: '/vagas/$slug'
      preLoaderRoute: typeof VagasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VagasSlugRoute: VagasSlugRoute,
  VagasIndexRoute: VagasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
